// AUM Measures

Total AUM = 
SUM(fact_aum_daily[market_value_base_currency])

AUM by Client = 
CALCULATE(
    [Total AUM],
    VALUES(dim_client[client_id])
)

AUM YoY Growth = 
VAR CurrentAUM = [Total AUM]
VAR PreviousYearAUM = 
    CALCULATE(
        [Total AUM],
        DATEADD(dim_date[date_value], -1, YEAR)
    )
RETURN
    DIVIDE(CurrentAUM - PreviousYearAUM, PreviousYearAUM, 0)

